project_id = "szciplghslorfjqgmuxc"

[functions.analyze-image]
verify_jwt = false

[functions.generate-toy-story]
verify_jwt = false

[functions.process-order]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false